inherit_from: configs/TUM_RGBD/tum.yaml
mapping:
  bound: [[-5., 5.], [-5., 5.], [-5., 5.]]
  marching_cubes_bound: [[-5., 5.], [-5., 5.], [-5., 5.]]
data:
  input_folder: Datasets/TUM/rgbd_dataset_freiburg1_room
  output: output/TUM_RGBD/rgbd_dataset_freiburg1
cam: #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  crop_size: [384, 512]
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
