inherit_from: configs/7Scenes/7scenes.yaml
mapping:
  bound: [[-8., 8.], [-8., 8.], [-8., 8.]]
  marching_cubes_bound: [[-8., 8.], [-8., 8.], [-8., 8.]]
data:
  input_folder: Datasets/7-Scenes/redkitchen/seq-01
  output: output/7-Scenes/redkitchen/seq-01
